# frozen_string_literal: true

require "thermite/tasks"
require_relative "../lib/rusty_swiss_village_directory/thermite_initialize"

project_toplevel_dir = File.dirname(__dir__)
Thermite::Tasks.new(cargo_project_path: project_toplevel_dir,
                    ruby_project_path: project_toplevel_dir)

task default: "thermite:build"
